### ISSUE TITLE
pip command is not working. 

### ISSUE THREAD

**Issue by abhinavgudipati** [sanderlab/CellBox#16]
Hey there! 

<img width="926" alt="Screenshot 2021-02-18 at 4 54 45 PM" src="https://user-images.githubusercontent.com/53547094/108350234-025fbc00-720a-11eb-9f4b-02832dda145a.png">

I have tried to run the command as suggested in the readme.md but was not able to figure out a way to come across this error.

<img width="1403" alt="Screenshot 2021-02-18 at 4 55 42 PM" src="https://user-images.githubusercontent.com/53547094/108350359-24593e80-720a-11eb-85a2-f9e6a23a9fab.png">

@cannin @DesmondYuan @judyueshen greatful if you could diagnose this error.

Thanking you!

**Comment by abhinavgudipati** [comment]
Looking forward to your prompt response! thanking you!

**Comment by DesmondYuan** [comment]
Sorry for the late response. Closing because of redundancy. #18
