### ISSUE TITLE
pip command not working. #2 

### ISSUE THREAD

**Issue by abhinavgudipati** [sanderlab/CellBox#18]
<img width="1150" alt="Screenshot 2021-02-18 at 5 07 56 PM" src="https://user-images.githubusercontent.com/53547094/108351683-d9402b00-720b-11eb-938a-523e87e55724.png">

I have already discussed this issue previously. I have tried both methods of installation.

pip3 as well as pip. But both are persistently giving me errors. Looking forward to know how to work around this error. 

Thanking you! 

@cannin @DesmondYuan @judyueshen

**Comment by abhinavgudipati** [comment]
Looking forward to your prompt response! thanking you!

**Comment by DesmondYuan** [comment]
@abhinavgudipati thanks for the question. 

I could not reproduce your error. Can you specify which python and pip version are you using?

Also this seems like an error of pip and is independent to which package you install. See some of the discussions [here](https://github.com/pypa/pip/issues/5271) and [here](https://github.com/pypa/packaging-problems/issues/252). Not sure if they are related though. But I would try to upgrade pip to the latest version and try again. 

PS: you can specify which branch to install other than `version_for_revision` which is actually an outdated branch.

**Comment by abhinavgudipati** [comment]
I was able to figure this issue! Apologies for late update! Thanking for your attention!  @DesmondYuan
