### ISSUE TITLE
installing required modules from requirements.txt

### ISSUE THREAD

**Issue by guptadhaval18** [sanderlab/CellBox#19]
After creating new environment. While running cellbox/setup.py, I had to manually install h5py module. So, I think it would be better to mention it in setup.py or install all modules mentioned in requirements.txt while running setup.py.
If you agree. I will send a pull request.

**Comment by DesmondYuan** [comment]
Hi sorry for the late reply. But the `hp5y` should already be in the `requirements.txt` during `pip` installation. See more [here](https://github.com/sanderlab/CellBox/blob/4d5195b37d3df883b7ff2a1700662442d6bbd355/requirements.txt#L6)
