### ISSUE TITLE
expr_index

### ISSUE THREAD

**Issue by notimenocall** [sanderlab/CellBox#22]
Hi,
A naive question here. What do column 2 and 3 in expr_index.txt indicate?
Thanks,
Xiao

**Comment by DesmondYuan** [comment]
Hi Xiao, apologies for the late reply. It is the original data file we received from the data [paper](https://elifesciences.org/articles/04640) and is only used as a reference for the condition names. In other words the 2nd and 3rd columns are not being used in CellBox.
