### ISSUE TITLE
pip install seems broken

### ISSUE THREAD

**Issue by Teculos** [sanderlab/CellBox#40]
The install instructions for pip don't seem to work, checked on a mac and linux system.

**Comment by cannin** [comment]
Try this: 

```
pip install git+https://github.com/dfci/CellBox.git@cell_systems_final#egg=cellbox\&subdirectory=cellbox
```

NOTE: I do not believe it has ever been tested on a Mac with ARM-based CPU.

**Comment by Teculos** [comment]
Yes this did work! Thanks for the quick response

**Comment by Teculos** [comment]
The suggested solution, while allowing me to install cellbox, seems to have it break for the single_to_combo.json file included in the repo. 

Specifically it looks like the `cellbox.dataset.factory` function installed from the previous suggestion differs from the one in the sanderlab github repo. Specifically it seems to omit lines 27-31 found [here](https://github.com/sanderlab/CellBox/blob/master/cellbox/cellbox/dataset.py). Which breaks the `s2c` function downstream. I'm going to try and install directly from the included setup.py but wanted to mention it to yall

Also just fyi, it seems to work perfectly fine for random partition and minimal config examples.
