### ISSUE TITLE
Update CellBox README

### ISSUE THREAD

**Issue by Mustardburger** [sanderlab/CellBox#51]
This issue is for updating the README file for future users to better install and use CellBox.

**Comment by cannin** [comment]
Quick comment: If there is something that you think would help a user, but don't see a good location (as is) for it in the README, then make a Tips or Notes or Troubleshooting section (not sure what's the best name).

**Comment by Mustardburger** [comment]
Dear Augustin,

Sure! Is this section also in the README, maybe at the bottom of the file,
or would you like me to create a Wiki section on Github for this section?

Best regards,
Phuc Nguyen

**Comment by cannin** [comment]
@Mustardburger no wiki unless it becomes incredibly long; I expect that will not happen

**Comment by Mustardburger** [comment]
I see, then I can add it as a section at the end of the README.
